# Generated by Django 4.1.2 on 2022-10-25 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Charts', '0002_rename_name_order_category_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'product'},
        ),
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='order',
            name='location',
            field=models.CharField(default='Maasai shop ', max_length=20),
        ),
    ]
